spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/redNoseDataBase?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: red-nose-admin
    password: red-nose-admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://mongo-admin:mongo-admin@mongodb:27017/redNoseDataBase?authSource=admin

  servlet:
    multipart:
      max-file-size: 1200MB
      max-request-size: 1200MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    gcp:
      credentials:
        location: classpath:red-nose-project-d487e1027b27.json
      storage:
        project-id: red-nose-project
        bucket: red-nose-bucket
        bucket-dir-path: https://storage.googleapis.com/red-nose-bucket/

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: afca8ff5e95b185b20d7c539a1089a1b
            client-secret: nFSru8vaOlygJdAUP5hAsd94gmzkwwDo
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: https://red-nosed.com/login/oauth2/code/kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secretKey: asdfasdfasdfasdrtqwetqpkna;pilugipk1j23k4lhj1adfkj9312kl3n@*!!~asdkflj9@#Nvlny.asdf

  access:
    expiration: 604800000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: ReAuthorization



